version: "3.1"

services:
  mongo_one:
    container_name: mongo1
    image: mongo:latest
    command: mongod --replSet my-mongo-set
    ports:
      - 27001:27017
    volumes:
      - /data/mongodb/mongo1:/data/db
    restart: always
    networks:
      mongo-cluster:
        ipv4_address: 172.18.0.2

  mongo_two:
    container_name: mongo2
    image: mongo:latest
    command: mongod --replSet my-mongo-set
    ports:
      - 27002:27017
    volumes:
      - /data/mongodb/mongo2:/data/db
    restart: always
    networks:
      mongo-cluster:
        ipv4_address: 172.18.0.3

  mongo_three:
    container_name: mongo3
    image: mongo:latest
    command: mongod --replSet my-mongo-set
    ports:
      - 27003:27017
    restart: always
    volumes:
      - /data/mongodb/mongo3:/data/db
    networks:
      mongo-cluster:
        ipv4_address: 172.18.0.4

networks:
  mongo-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
